version: '3.4'

services:
  image.api:
    image: imageapi:dev
    container_name: Image.Api
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "Image.Api"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_image.api$
    volumes:
      - C:\Users\zivko\source\repos\DockerDemo\Image.Api:/app
      - C:\Users\zivko\source\repos\DockerDemo:/src
      - C:\Users\zivko\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_image.api$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_image.api$ \"/app/bin/Debug/netcoreapp3.1/Image.Api.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true
  imagegallery.web:
    image: imagegalleryweb:dev
    container_name: ImageGallery.Web
    build:
      target: build
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "ImageGallery.Web"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_imagegallery.web$
    volumes:
      - C:\Users\zivko\source\repos\DockerDemo\ImageGallery.Web:/app
      - C:\Users\zivko\source\repos\DockerDemo:/src
      - C:\Users\zivko\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_imagegallery.web$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_imagegallery.web$ \"/app/bin/Debug/netcoreapp3.1/ImageGallery.Web.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true
